service: sechub

frameworkVersion: "2"

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-stack-termination-protection
  - serverless-idempotency-helper
  - serverless-iam-helper
  - serverless-s3-bucket-helper
  - serverless-online

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  serverlessTerminationProtection:
    stages:
      - master
      - val
      - production
  githubAccessToken: ${ssm:/configuration/${self:custom.stage}/sechub/githubAccessToken~true, ssm:/configuration/default/sechub/githubAccessToken~true}
  githubRepository: ${ssm:/configuration/${self:custom.stage}/sechub/githubRepository~true, ssm:/configuration/default/sechub/githubRepository~true, env:GITHUB_REPOSITORY}
  githubRepositoryProjects: ${ssm:/configuration/${self:custom.stage}/sechub/githubRepositoryProjects~true, ssm:/configuration/default/sechub/githubRepositoryProjects~true, ""}
  githubOrganizationProjects: ${ssm:/configuration/${self:custom.stage}/sechub/githubOrganizationProjects~true, ssm:/configuration/default/sechub/githubOrganizationProjects~true, ""}
  severity: ${ssm:/configuration/${self:custom.stage}/sechub/severity~true, ssm:/configuration/default/sechub/severity~true, "CRITICAL,HIGH"}

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  iam:
    role:
      path: ${ssm:/configuration/${self:custom.stage}/iam/path~true, ssm:/configuration/default/iam/path~true, "/"}
      permissionsBoundary: ${ssm:/configuration/${self:custom.stage}/iam/permissionsBoundaryPolicy~true, ssm:/configuration/default/iam/permissionsBoundaryPolicy~true, ""}
      statements:
        - Effect: "Allow"
          Action:
            - securityhub:GetFindings
          Resource:
            - !Sub arn:aws:securityhub:*:${AWS::AccountId}:hub/default
functions:
  scan:
    handler: handlers/scan.main
    timeout: 600
    maximumRetryAttempts: 0
    environment:
      githubAccessToken: ${self:custom.githubAccessToken}
      githubRepository: ${self:custom.githubRepository}
      githubRepositoryProjects: ${self:custom.githubRepositoryProjects}
      githubOrganizationProjects: ${self:custom.githubOrganizationProjects}
      severity: ${self:custom.severity}
      stage: ${self:custom.stage}
