service: database

frameworkVersion: "2"

plugins:
  - serverless-dynamodb-local
  - serverless-stack-termination-protection
  - serverless-deployment-bucket

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  serverlessTerminationProtection:
    stages: # This is a list of common names for important envs that should not be destroyed.  You can remove the stage names your project doesn't use; this list is meant to be inclusive.
      - master
      - val
      - production
      - develop
      - main
      - impl
      - val
      - prod
  tableName: ${self:custom.stage}-amendments
  dynamodb:
    stages:
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true
  deploymentBucket:
    versioning: true

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  deploymentBucket:
    name: ${file(./../../libs/accountId.js):accountId}-sdb-${self:service}-${self:custom.stage}
    maxPreviousDeploymentArtifacts: 1
    serverSideEncryption: AES256
    tags:
      STAGE: ${self:custom.stage}

resources:
  Resources:
    AmendmentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: amendmentId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: amendmentId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST # Set the capacity to auto-scale
    AmendmentsAtomicCounterTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}-atomic-counter
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST # Set the capacity to auto-scale
  Outputs:
    AmendmentsTableName:
      Value: !Ref AmendmentsTable
    AmendmentsTableArn:
      Value: !GetAtt AmendmentsTable.Arn
    AmendmentsTableStreamArn:
      Value: !GetAtt AmendmentsTable.StreamArn
    AmendmentsAtomicCounterTableName:
      Value: !Ref AmendmentsAtomicCounterTable
    AmendmentsAtomicCounterTableArn:
      Value: !GetAtt AmendmentsAtomicCounterTable.Arn
    Region:
      Value: !Sub ${AWS::Region}
